spring.application.name=scrs
spring.datasource.url=jdbc:mysql://localhost:3306/scrs_db
spring.datasource.username=root
spring.datasource.password=single007
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080
spring.jackson.deserialization.fail-on-null-for-primitives=false